<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GameTestProject>true</GameTestProject>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <NoWarn>$(NoWarn);CA1861;CA1859;CA1707;xUnit2013;xUnit2029</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Lumio.Game.ServerGameplay/Lumio.Game.ServerGameplay.csproj" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Testing.Platform" />
    <PackageReference Include="coverlet.MTP" />
  </ItemGroup>
</Project>
